### ISSUE TITLE
Crash on iphonesim at runtime with simple Cocktail/video application

### ISSUE THREAD

**Issue by zabojad** [nmehost/nme#11]
Hugh,

I've successfully built my simple Cocktail/video app with the iphonesim nme target. I can open it in XCode and build/run on the iphone simulator.

Now at runtime/startup of the app, I have the following crash:

![screen shot 2014-04-29 at 13 42 58](https://cloud.githubusercontent.com/assets/1238030/2828504/b76fc498-cf94-11e3-8c36-1a3c2c68ebe0.png)

Any idea where it comes from ?

Thanks,

Thomas

**Comment by hughsando** [comment]
So it looks like a null WeakRef has been created.  It may be possible to
add a null-check at this point where it has crashed, but I would like to
work out why it is null in the first place.
Is this only happening with the video?  There might be some weakrefs in
there.

**Comment by zabojad** [comment]
Hi Hugh !

Adding the -debug flag in nme compilation command line give me those logs when it crashes at startup:

```
VIDEO: play videos_wwx2014_mp4.mp4 0.000000 -1.000000
===== recreateNmeView ===== 0
VIDEO: play videos_wwx2014_mp4.mp4 0.000000 -1.000000
VIDEO: play videos_wwx2014_mp4.mp4 0.000000 -1.000000
GL Error: 1282 480x320
on Finished 1
force stop
playback error
2014-05-04 13:19:46.893 MyApp[4223:907] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'An AVPlayerItem cannot be associated with more than one instance of AVPlayer'
*** First throw call stack:
(0x39be012 0x3bf3e7e 0x28e7728 0x28dae6a 0x28dacf3 0x28f6bb0 0x20bdedc 0x209ae2e 0x667053f 0x6682014 0x66727d5 0x3964af5 0x3963f44 0x3963e1b 0x39187e3 0x3918668 0x1144ffc 0x6b28 0x4eff0 0x860599 0x89f084 0x35177d 0x8308d4 0x834757 0x892d70 0x2a63 0x2a25 0x1)
libc++abi.dylib: terminate called throwing an exception
(lldb) 
```

Then, removing all the video from my little app doesn't solve my problem. It still crashes at startup but I'm not sure if it's the same problem... Here is what I have in XCode in that case:

![screen shot 2014-05-04 at 13 32 38](https://cloud.githubusercontent.com/assets/1238030/2872902/054db08c-d380-11e3-8569-8fe5e6b786b2.png)

![screen shot 2014-05-04 at 13 34 44](https://cloud.githubusercontent.com/assets/1238030/2872905/35e6ac0c-d381-11e3-9269-586a86b56836.png)

It seems to be crashing on cocktail.port.platform.flash_player.GraphicsSurface.drawImage(). I've added some logs and this method is called many times without crashing before it happens.

Do you have any idea about why it's crashing ?

Thanks 
Thomas

**Comment by zabojad** [comment]
I forgot: would it help if I share with you on bitbucket this little project ?

**Comment by zabojad** [comment]
Hey Hugh, what would you suggest in order to find the root cause of this crash ?

**Comment by hughsando** [comment]
Hi
Sorry have not got back to you earlier.
This looks like "force stop" is being called from a finalizer, which I
guess could be ok, but maybe not.
I think this was an IOS 6 thing - there was something to do with the order
of stopping and setting the next item.
Maybe the video object is removed without calling "stop", or our internal
state does not know that stop has been called somehow and decides to call
it again.
Can you work with ios7? :)
I will see what I can do, but I suspect it is to do with the order of
calling "play", "stop" and adding/removing from stage.

**Comment by zabojad** [comment]
Hi Hugh, 
It's not related to the video. I've completely removed it from my app code. It seems to happen in nme.display.BitmapData.nmeDrawToSurface() when Cocktail needs to draw some element background.
I will check if it happens on the ios 7 simulator and device as well...
Thanks
Thomas

**Comment by hughsando** [comment]
Ok, so if it crashing in "run finalizers", like in the top expanded call
stack, it looks like a bug with the weak reference code, or maybe a null
weak reference.
This could show up in anything - not just the draw image call - just luck
maybe.
Do you you weak references explicitly? The other one is weak event handlers
- there might be a problem here - this would probably crash on desktop code
  too then.
  Maybe the weak reference code is interfering with the member closure code,
  which changed a few months ago.
  If I can get a reproducible sample, it should not be too hard to fix

**Comment by zabojad** [comment]
I've shared with you my little demo app on bitbucket.
I've commented all the video stuff in it.

**Comment by hughsando** [comment]
Ok, I've made a fix to hxcpp.  There was a null weak-ref being generated by
the nme asset cache.  Maybe there was an asset missing?  Anyhow, it should
not crash with the hxcpp fix.

Also, nme and lime code bases have been re-unified to github haxenme/nme
now.  The nmehost version contains the current official haxelib version on
NME, but the next one will come from the new (or old, depending on how you
look at it) repo.  This should allow bug fixes to be shared from lime,
while also keeping individual lime/nme identities.

**Comment by zabojad** [comment]
Hugh, thanks for the hxcpp fix. How can I recompile hxcpp ? The build files have moved since the last time I did that...

Here is what I've tried:

```
haxelib run hxcpp BuildCommon.xml 
Error: Could not find dependencies: [ Options.txt ]
```

**Comment by zabojad** [comment]
Is it now the Build.xml that is in hxcpp/project/ we should run with "haxelib run hxcpp " to build hxcpp ?

**Comment by zabojad** [comment]
Ok, I think I've made it with building hxcpp. However with nme from repo, I get this:

```
haxelib run hxcpp Build.xml 
Error: Could not find haxelib "nme-dev", does it need to be installed?
```

A mistake in the Build.xml file ?

```
   <!-- Where to find static libraries/includes -->
   <set name="NME_DEV" value="${haxelib:nme-dev}" unless="NME_DEV" />
```

**Comment by zabojad** [comment]
I found it ! Explained [there](https://github.com/openfl/openfl/wiki/1.2.-Install-Lime)

That library isn't hosted on haxelib that's why I thought it was a mistake...

**Comment by hughsando** [comment]
You can get it from:
https://github.com/haxenme/nme-dev
and then "haxelib dev nme-dev ~/.../nme-dev

To build this, and nme and hxcpp, it is:
cd project
neko build.n ios
(or just "neko build.n" for desktop)
this will build the different combos of binaries.

**Comment by zabojad** [comment]
Thanks Hugh, one last problem with building:

After having successfully ran `neko build.n`, `neko build.n ios`and `neko build.n android` for both hxcpp and nme-dev, I now have a crash when running `neko build.n`on nme:

```
neko build.n 
Usage : neko build.n [clean] [link-]target[-arch][-arch] ...] [-debug] [-verbose] [-D...]
  target  : ios, android, windows, linux, mac
            default (=current system)
  link    : ndll- or static-
            (none specified = both link types
  arch    : -armv5 -armv6 -armv7 -arm64 -x86 -m32 -m64
            (none specified = all valid architectures
  -D...   : defines passed to hxcpp build system
 eg: neko build.n clean ndll-mac-m32-m64 = rebuild both mac ndlls
 Specify target or 'default' to remove this message

Using default = mac

Build mac, link=ndll arch=m64
haxelib run hxcpp Build.xml -Dmac -DHXCPP_M64 
g++ -I../include -Iinclude -I/Users/thomasfetiveau/wksp_wwx2014/nme-dev/include/SDL2 -DSDL_OGL -DNME_MIXER -DNME_SDL2 -DNME_CURL_SSL -I/Users/thomasfetiveau/wksp_wwx2014/nme-dev/include -D_7ZIP_ST -c -fvisibility=hidden -stdlib=libstdc++ -O2 -I/Users/thomasfetiveau/wksp_wwx2014/hxcpp/include -DHX_MACOS -m64 -Wno-parentheses -Wno-unused-value -Wno-format-extra-args -DHXCPP_M64 -DHXCPP_VISIT_ALLOCS -DHXCPP_API_LEVEL=0 -x objective-c ./src/mac/MacBoot.m -oobj/darwin64/863e6973_MacBoot.o

(...)

Error: In file included from ./src/common/ExternalInterface.cpp:16:
In file included from include/Utils.h:4:
In file included from /Users/thomasfetiveau/wksp_wwx2014/hxcpp/include/hx/CFFI.h:93:
/Users/thomasfetiveau/wksp_wwx2014/hxcpp/include/hx/CFFILoader.h:100:42: error: expected ')'
      sNekoDllHandle = dlopen("libneko." NEKO_EXT, RTLD_NOW);
                                         ^
/Users/thomasfetiveau/wksp_wwx2014/hxcpp/include/hx/CFFILoader.h:100:30: note: to match this '('
      sNekoDllHandle = dlopen("libneko." NEKO_EXT, RTLD_NOW);
                             ^
/Users/thomasfetiveau/wksp_wwx2014/hxcpp/include/hx/CFFILoader.h:103:45: error: expected ')'
         sNekoDllHandle = dlopen("libneko." NEKO_EXT ".0", RTLD_NOW);
                                            ^
/Users/thomasfetiveau/wksp_wwx2014/hxcpp/include/hx/CFFILoader.h:103:33: note: to match this '('
         sNekoDllHandle = dlopen("libneko." NEKO_EXT ".0", RTLD_NOW);
                                ^
2 errors generated.
#### Error building m64
```

Any idea why ?

**Comment by zabojad** [comment]
However `neko build.n ios`and `neko build.n android` work fine on nme...

**Comment by zabojad** [comment]
Hmmm actually, I might have a problem, compiling my demo app with nme gives:

```
haxelib run nme build iphonesim
Called from sys.io.FileOutput::$statics line 1
Called from CommandLineTools::main line 1027
Called from nme.net.SharedObject::getLocal line 156
Called from nme.net.SharedObject::getFilePath line 127
Called from nme.filesystem.File::get_applicationStorageDirectory line 36
Uncaught exception - Invalid call
```

**Comment by zabojad** [comment]
Just to recap, here is my `haxelib list` output, with hxcpp, nme-dev and nme freshly recompiled (except `neko build.n` that crashed with nme as I wrote earlier):

```
haxelib list
cocktail: [dev:/Users/thomasfetiveau/wksp_wwx2014/cocktail]
format: 3.0.4 [3.0.5]
haxelib_client: 3.1.0-rc.3 [3.1.0-rc.4]
hxcpp: 3.1.30 [dev:/Users/thomasfetiveau/wksp_wwx2014/hxcpp]
hxlibc: [1.1.4]
nme-dev: [dev:/Users/thomasfetiveau/wksp_wwx2014/nme-dev]
nme-state: [1.2.4]
nme: 5.0.37 [dev:/Users/thomasfetiveau/wksp_wwx2014/nme]
svg: [1.0.7]
utest: [1.1.3]
```

**Comment by hughsando** [comment]
I've fixed the mac hxcpp issue - seems like some merge went wrong today.

**Comment by zabojad** [comment]
Cool! So now:
- now nme compiles
- my app compiles with nme
- my app doesn't crash anymore in iphone emulator

Thanks Hugh ;) !

**Comment by hughsando** [comment]
Music to my ears.
