### ISSUE TITLE
512 Header size limited in CURL

### ISSUE THREAD

**Issue by mikestead** [nmehost/nme#12]
Hi, I submitted a fix to CURL.cpp in Lime a while back to support headers larger than the current 512 limit. It looks like that has not made it's way into NME during the move back to use NME for OpenFl. Is there any plan to merge fixes from Lime > NME or should I open a new pull request?

See original here: https://github.com/openfl/lime/pull/29

**Comment by hughsando** [comment]
NME and lime have been reunified in https://github.com/haxenme/nme so your changes should be in there I think.

**Comment by mikestead** [comment]
Great thanks Hugh
