### ISSUE TITLE
glUniformMatrixXfv

### ISSUE THREAD

**Issue by delahee** [nmehost/nme#2]
...Implementation and vertexAttrib currently is not respecting opengl spec and does not allow matrix palettes.

I submitted fixes to openfl and lime, can you please fix ?

**Comment by hughsando** [comment]
Hi,
I'm having trouble working out which code you are talking about - it might have pre-dated the move to lime.  Was it haxe or cpp code?  Is it the uniformMatrix2fv/uniformMatrix3fv/uniformMatrix4fv functions, or something else.

**Comment by delahee** [comment]
The code is both the .hx and .cpp.
Problem in .hx is that they take array of double instead of float buffers
which is hugely inefficient on mobile for high bandwidth needs ( like
uploading matrix palettes). If you want no regression (albeit minor) we
must separate calls because current type interprétation is odd.

Problem in cpp is that uniformXfv and uniform matrix and
vertexattribpointerXfv are not respecting gl semantics about the count
param and that impeach any use of gl arrays such as matrux palettes or
multi lights.

I ll fetch you the link in further comment since am out of town.
Thx
 Le 19 mars 2014 06:44, "Hugh Sanderson" notifications@github.com a
écrit :

**Comment by dazKind** [comment]
here are some example locations:
https://github.com/nmehost/nme/blob/master/project/src/opengl/OGLExport.cpp#L837
https://github.com/nmehost/nme/blob/master/project/src/opengl/OGLExport.cpp#L902

I also supplied some ogl patches to lime. Im still working out how much it really differs from this and if the fixes matter for nme. Most of my fixes seem to patch code parts that were created to replace the nme resoucesystem. Still confused about the whole openfl/lime/nme topic.

**Comment by delahee** [comment]
And here is what you can backmerge : 
https://github.com/motion-twin/lime/blob/master/lime/gl/native/GL.hx
https://github.com/motion-twin/lime/blob/master/project/src/renderer/opengl/OGLExport.cpp

If you could do this, it would be cool because then h3d animations and light system would work for everyone.

**Comment by delahee** [comment]
Actually it is :https://github.com/nmehost/nme/blob/master/project/src/opengl/OGLExport.cpp#L968 and its little friends. I advise you diff the whole files and study what we improved ( at Motion-twin)

you will find code that should be backmerged here : 
https://github.com/motion-twin/lime/blob/master/lime/gl/native/GL.hx
and here https://github.com/motion-twin/lime/blob/master/project/src/renderer/opengl/OGLExport.cpp

Lime has not made the fix but if you could make it it would be awesome, that way everyon could use h3d animation+light  or simply enjoy bone animation on mobile.

Thanks a lot for your future users !

**Comment by hughsando** [comment]
Great - I will have a look.  It may get a bit tricky on the merge, because I have changed from raw IDs for textures/programs/shaders etc to abstracts/objects, to allow auto-cleanup.  And yes, I will have to mentally replace "lime" with "nme" in the source code.

**Comment by hughsando** [comment]
So basically replace Array<Float> with Float32Array? (Array<Int> too I guess)
I think the uniformXfv calls are going to be more convenient as arrays, like;

uniform3fv([1.0,2,3]);

Unless you have already pre-calculated a big array and are using an offset - is this what is happening?
It should be possible to support both ways with the one function and not break anything.

**Comment by delahee** [comment]
@hughsando  in fact not exactly . Actually uniform3fv([1.0,2,3]); is the only valid call but instead uniform3fv([1.0,2,3, 1.0,2,15 , 1.0,2,9 , 1.0,2,6]);

The awesome issue is that uniform xv takes and uploads a stream of 3-uple and current implementation does not "understand that".

Basically uniformXfv is made for that, your example is a sort of abuse, uniform3f is for what you meants,

the real scheme of use of Xfv is
 floatbuffer f = new floatbuffer; 
_insert thousand of values_
 upload.

So those functions are made for extreme bandwith and cpu efficiency, so they should only be accessed with the right type.

[x,y,z] as Double is not acceptable as basic input sinceit requires on the fly conversion that is very expensive.

So we must basically replace the base Double (64 bit) array and ensure what is sent is an effective and tightly packed float (32bit) array.

the function shouldn't be clever at all, because it it basically a dma copy and it should stay like this.

I am open to sub functions that take same kind of input as what you suggested but the DMA copy of floats semantics must be restored :-D

**Comment by hughsando** [comment]
I see - I completely missed the "count" concept when I converted the webgl API. Makes lots of sense.

**Comment by delahee** [comment]
You are welcome bro, give us high bandwidth dma copy and let's make awesome games.

**Comment by hughsando** [comment]
I have put in the fix for uniformMatrixfv, and added array options for vertextAttribfv and  uniformfv.  I could really only give these a simple test - it would be great if you could verify whether they work.

**Comment by delahee** [comment]
Well looks nice, solution seems fine, I will test and keep you up.

2014-03-19 17:34 GMT+01:00 Hugh Sanderson notifications@github.com:

> I have put in the fix for uniformMatrixfv, and added array options for
> vertextAttribfv and uniformfv. I could really only give these a simple test
> - it would be great if you could verify whether they work.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nmehost/nme/issues/2#issuecomment-38073814
> .

## 

David Elahee

**Comment by delahee** [comment]
Ok I can't manage to dinf time to test as it would require me to setup an adequate nme workflow.

But I can help you test your fix is ok without adding palettes. 

Retrieve gDebugguer
Make your regular test but stuff an uniform call with an oversized array (it is harmless)
With gDebugguer you can spy uniform and vertex buffers and you should see your overflowing value in memory.

There you should be done, if it fails, i'll try to setup something but I have no time right now.
