### ISSUE TITLE
When Assets.getText, readUTFBytes throws "ThrowEOFi" due position non-zero

### ISSUE THREAD

**Issue by madrazo** [nmehost/nme#3]
Hi Huge.

Got this interruption "End of file was encountered", on windows (64bit?) target:

...
Called from nme.Assets::getText::nme/Assets.hx::382
Called from nme.utils.ByteArray::readUTFBytes::nme/utils/ByteArray.hx::336
Called from nme.utils.ByteArray::ThrowEOFi::nme/utils/ByteArray.hx::391

Tracing ByteArray.hx got this:
ByteArray.hx:335: position:13504, inLen 13504, length:13504

However, position should be 0 (as in OpenFL). 
If I force position to 0, compliles and runs OK. Not sure were "position" has been set.

Thanks!

**Comment by hughsando** [comment]
I have moved this repo to https://github.com/haxenme/nme, and it looks like position is set to 0 then in getBytes.  However, there might have been an issue with caching, which I hope I've fixed.  Please re-issue the bug on the new repo if there are still problems.

**Comment by madrazo** [comment]
Thanks!
