### ISSUE TITLE
retrieving ogl extensions function pointer

### ISSUE THREAD

**Issue by delahee** [nmehost/nme#4]
Hi,

How can i retrieve extensions pointer to use them ? 

for example QCOM_memory_monitor
http://www.cnblogs.com/hongzg1982/articles/2342130.html 

All i can think about is very overweight...any idea ?

**Comment by hughsando** [comment]
If you are using c++ exclusively, then there are some native extensions
that could do it. If you need neko too, then there is a hxffi library that
should work on the neko targets (may cause terms-of-service issues for
iOS?), so maybe between the two all bases could be covered.  Depending how
many extensions we are potentially talking about, it might be easier to add
them to nme.
Hugh

**Comment by delahee** [comment]
hmm ok i ll think of it.

**Comment by delahee** [comment]
ok we have rethinked the whole business. 

We need : https://www.opengl.org/wiki/Load_OpenGL_Functions to be accessible to end user in a programmatic way (what you already do with defines in fact ).

Can you do it please ? I believe you can do ti 100 time faster than I since you know the whole clockwork and have better understanding of what is possible.

If would be somethign like :

glGetProcAddress( name ) where name comes from getSupportedExtension and return a 

class glFunc {
 proc:Dynamic
///or
 execute(Dynamic) : Dynamic
}

I perfectly know it might be costy, but it would really help to be able to put up ith such construct to perform trial and errors of simple processes.

I have no problem with it only available on c++ because I don't use neko target.

Thanks a lot !

**Comment by hughsando** [comment]
The new cpp.Function class should be able to help here.  I'm closing this repo and moving back to https://github.com/haxenme/nme.  Please reissue the request there is you are still interested.
