### ISSUE TITLE
include tag on NMLL not working, parseXML is called twice

### ISSUE THREAD

**Issue by madrazo** [nmehost/nme#5]
When using the following on the nmml file, there is an error in NMMLParser.hx
<include path="myPath" />

The function parseXML on NMMLParser.hx is being called twice, and the second time with element.has.path set to false, which makes it run the following line:

path = findIncludeFile(PathHelper.combine(extensionPath, substitute(element.att.name)));

but element.att.name is null.

For now, I workaround it by setting a break from the switch on parseXML function (exits when it is called the second time) :

```
              else
              {
                 break; //This one
                 path = findIncludeFile(PathHelper.combine(extensionPath, substitute(element.att.name)));
              }
```

Cheers

**Comment by madrazo** [comment]
Ohh. It is called twice, because it is parsing the include.xml file. So, in this file there was a 
< include haxelib="openfl" />
which I dont really need, I think

I see that  lime-tools/project/ProjectXMLParser.hx
checks for a  element.has.haxelib
Just throwing a warning or ignoring it may may be enough to solve this compatibility issue.
Cheers

**Comment by hughsando** [comment]
I have moved this repo to https://github.com/haxenme/nme, and think I have fixed the problem there.  Please reissue the bug if it is still a problem.
