### ISSUE TITLE
ByteArray problems

### ISSUE THREAD

**Issue by PierBover** [nmehost/nme#6]
I'm trying to build the StageVideo sample and I get this:

/usr/lib/haxe/lib/nme/5,0,37/nme/utils/ByteArray.hx:241: lines 241-254 : Field readDouble should be declared with 'override' since it is inherited from superclass
/usr/lib/haxe/lib/nme/5,0,37/nme/utils/ByteArray.hx:241: lines 241-254 : Field readDouble overloads parent class with different or incomplete type
/usr/lib/haxe/lib/nme/5,0,37/nme/utils/ByteArray.hx:241: lines 241-254 : Void -> Float should be pos : Int -> Float
/usr/lib/haxe/lib/nme/5,0,37/nme/utils/ByteArray.hx:263: lines 263-276 : Field readFloat should be declared with 'override' since it is inherited from superclass
/usr/lib/haxe/lib/nme/5,0,37/nme/utils/ByteArray.hx:263: lines 263-276 : Field readFloat overloads parent class with different or incomplete type
/usr/lib/haxe/lib/nme/5,0,37/nme/utils/ByteArray.hx:263: lines 263-276 : Void -> Float should be pos : Int -> Float

**Comment by PierBover** [comment]
After trying to run a sample project on OpenFL I got the same errors...

I will close this issue, I presume the error is not in NME.

**Comment by hughsando** [comment]
Yes - this was the haxe upgrade.  I think there will be a haxe hotfix to
address this - or downgrade to the previous version.
