### ISSUE TITLE
Can't run the iphonesim target anymore

### ISSUE THREAD

**Issue by zabojad** [nmehost/nme#9]
Hi Hugh

I'm trying to run on the iphone simulator a little project made with Cocktail but the simulator doesn't start. I get this:

```
haxelib run nme test iphonesim

(...)

** BUILD SUCCEEDED **

dyld: Library not loaded: @rpath/iPhoneSimulatorRemoteClient.framework/Versions/A/iPhoneSimulatorRemoteClient
  Referenced from: /usr/lib/haxe/lib/nme/5,0,37/tools/run/bin/ios-sim
  Reason: image not found
```

My local setup is:

```
haxelib list
cocktail: [dev:/Users/thomasfetiveau/wksp_cocktail/cocktail]
format: 3.0.4 [3.0.5]
haxelib_client: 3.1.0-rc.3 [3.1.0-rc.4]
hxcpp: [3.1.30]
hxlibc: [1.1.4]
nme-state: [1.2.4]
nme: [5.0.37]
svg: [1.0.7]
```

Any idea why ?

Thanks

Thomas

**Comment by hughsando** [comment]
Hi,
I'm not too sure about how to debug the remote-client stuff.  If looks like
something may have changes with a OS upgrade or something.  YOu should be
able to test from xcode, but I will have to look at how this launcher works.

**Comment by zabojad** [comment]
Yes my XCode updated recently...

I'll see if I can launch it from XCode or come back to previous a XCode version...

**Comment by hughsando** [comment]
I'm closing this - you can reissue on if https://github.com/haxenme/nme if there is still a problem.
